<?php
define( 'DB_HOST', ''); // EN ESTA VARIABLE SE DEFINE EL HOST EN DONDE ESTA ALOJADA LA BASE DE DATOS e.g: localhost
define( 'DB_USER', ''); // ESTA VARIABLE DEFINE EL USUARIO DE LA BASE DE DATOS e.g: jperez
define( 'DB_PASSWORD', ''); // ESTA VARIABLE CONTIENE LA CONTRASEÑA A LA BASE DE DATOS DEL USUARIO DEFINIDO e.g: 1234DBmanager
define( 'DB_NAME', ''); // ESTA VARIABLE DEBE CONTENER EL NOMBRE DE LA BASE DE DATOS e.g: dbrastreador
?>